export interface Politician {
  id: string;
  name: string;
  title: string;
  party: "Democrat" | "Republican" | "Independent" | "Nonpartisan";
  office: string;
  region: string;
  level: "federal" | "state" | "county" | "local";
  imageUrl?: string;
  bio: string;
  keyIssues: string[];
  website?: string;
  socialHandles?: {
    x?: string;
    facebook?: string;
    instagram?: string;
    youtube?: string;
    linkedin?: string;
    threads?: string;
  };
  phone?: string;
  email?: string;
  contactForm?: string;
}

export const nevadaPoliticians: Politician[] = [
  // ═══════════════════════════════════════════════════════
  // FEDERAL — U.S. Senators
  // ═══════════════════════════════════════════════════════
  {
    id: "cortez-masto",
    name: "Catherine Cortez Masto",
    title: "U.S. Senator",
    party: "Democrat",
    office: "U.S. Senate",
    region: "State of Nevada",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/C/C001113.jpg",
    bio: "Catherine Cortez Masto is the senior U.S. Senator from Nevada, first elected in 2016. She is the first Latina elected to the U.S. Senate and focuses on immigration, healthcare, and clean energy.",
    keyIssues: ["Immigration Reform", "Healthcare", "Clean Energy", "Public Lands"],
    website: "https://www.cortezmasto.senate.gov",
    socialHandles: { x: "SenCortezMasto", facebook: "SenatorCortezMasto", instagram: "sencortezmasto", youtube: "SenatorCortezMasto" },
    phone: "(202) 224-3542",
    contactForm: "https://www.cortezmasto.senate.gov/contact",
  },
  {
    id: "rosen",
    name: "Jacky Rosen",
    title: "U.S. Senator",
    party: "Democrat",
    office: "U.S. Senate",
    region: "State of Nevada",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/R/R000608.jpg",
    bio: "Jacky Rosen is the junior U.S. Senator from Nevada, elected in 2018 and re-elected in 2024. A former computer programmer, she champions technology, veterans' issues, and workforce development.",
    keyIssues: ["Technology", "Veterans Affairs", "Workforce Development", "Small Business"],
    website: "https://www.rosen.senate.gov",
    socialHandles: { x: "SenJackyRosen", facebook: "SenJackyRosen", instagram: "senjackyrosen", youtube: "SenatorJackyRosen" },
    phone: "(202) 224-6244",
    contactForm: "https://www.rosen.senate.gov/contact",
  },

  // ═══════════════════════════════════════════════════════
  // FEDERAL — U.S. Representatives
  // ═══════════════════════════════════════════════════════
  {
    id: "titus",
    name: "Dina Titus",
    title: "U.S. Representative",
    party: "Democrat",
    office: "U.S. House (NV-1)",
    region: "Central Las Vegas",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/T/T000468.jpg",
    bio: "Dina Titus represents Nevada's 1st Congressional District covering central Las Vegas, including the Strip. A former political science professor, she focuses on tourism, transportation, and veterans' affairs.",
    keyIssues: ["Tourism", "Transportation", "Veterans Affairs", "Foreign Affairs"],
    website: "https://titus.house.gov",
    socialHandles: { x: "RepDinaTitus", facebook: "CongresswomanTitus", instagram: "repdinatitus" },
    phone: "(202) 225-5965",
  },
  {
    id: "amodei",
    name: "Mark Amodei",
    title: "U.S. Representative",
    party: "Republican",
    office: "U.S. House (NV-2)",
    region: "Northern Nevada / Reno",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/A/A000369.jpg",
    bio: "Mark Amodei represents Nevada's 2nd Congressional District covering Reno and rural northern Nevada. He focuses on public lands, mining, and fiscal responsibility.",
    keyIssues: ["Public Lands", "Mining", "Fiscal Responsibility", "Water Rights"],
    website: "https://amodei.house.gov",
    socialHandles: { x: "MarkAmodeiNV2", facebook: "MarkAmodeiNV2" },
    phone: "(202) 225-6155",
  },
  {
    id: "lee",
    name: "Susie Lee",
    title: "U.S. Representative",
    party: "Democrat",
    office: "U.S. House (NV-3)",
    region: "Southern Nevada / Henderson",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/L/L000590.jpg",
    bio: "Susie Lee represents Nevada's 3rd Congressional District covering suburban Las Vegas and Henderson. She focuses on education, healthcare, and environmental protection.",
    keyIssues: ["Education", "Healthcare", "Environment", "Gun Safety"],
    website: "https://susielee.house.gov",
    socialHandles: { x: "RepSusieLee", facebook: "RepSusieLee", instagram: "repsusielee" },
    phone: "(202) 225-3252",
  },
  {
    id: "horsford",
    name: "Steven Horsford",
    title: "U.S. Representative",
    party: "Democrat",
    office: "U.S. House (NV-4)",
    region: "North Las Vegas / Rural Nevada",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/H/H001066.jpg",
    bio: "Steven Horsford represents Nevada's 4th Congressional District. He focuses on economic equity, labor rights, and community investment in underserved areas.",
    keyIssues: ["Labor Rights", "Economic Equity", "Community Investment", "Healthcare Access"],
    website: "https://horsford.house.gov",
    socialHandles: { x: "RepHorsford", facebook: "RepHorsford", instagram: "rephorsford" },
    phone: "(202) 225-9894",
  },

  // ═══════════════════════════════════════════════════════
  // STATE — Constitutional Officers
  // ═══════════════════════════════════════════════════════
  {
    id: "lombardo",
    name: "Joe Lombardo",
    title: "Governor",
    party: "Republican",
    office: "Governor of Nevada",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://gov.nv.gov/wp-content/uploads/2024/02/jl-headshot-1-scaled.jpg",
    bio: "Joe Lombardo is the 31st Governor of Nevada, having taken office in January 2023. A former Clark County Sheriff, he focuses on public safety, economic growth, and education reform.",
    keyIssues: ["Public Safety", "Economic Development", "Education", "Water Conservation"],
    website: "https://gov.nv.gov",
    socialHandles: { x: "JoeLombardoNV", facebook: "JoeLombardoNV", instagram: "joelombardonv" },
    phone: "(775) 684-5670",
  },
  {
    id: "anthony",
    name: "Stavros Anthony",
    title: "Lieutenant Governor",
    party: "Republican",
    office: "Lt. Governor of Nevada",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://ltgov.nv.gov/wp-content/uploads/2023/01/stavros-anthony-headshot.jpg",
    bio: "Stavros Anthony is the Lieutenant Governor of Nevada. A former Las Vegas City Councilman and UNLV professor, he presides over the Nevada Senate and chairs the Nevada Commission on Tourism.",
    keyIssues: ["Tourism", "Economic Development", "Small Business", "Veterans"],
    website: "https://ltgov.nv.gov",
    socialHandles: { x: "prior_stavros", facebook: "StavrosAnthonyNV" },
    phone: "(775) 684-7111",
  },
  {
    id: "ford",
    name: "Aaron D. Ford",
    title: "Attorney General",
    party: "Democrat",
    office: "Nevada Attorney General",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://ag.nv.gov/wp-content/uploads/2024/09/AGFord_Official-scaled.jpg",
    bio: "Aaron D. Ford is Nevada's 34th Attorney General, taking office in 2019. He focuses on consumer protection, criminal justice reform, and protecting Nevada's elections.",
    keyIssues: ["Consumer Protection", "Criminal Justice Reform", "Election Integrity", "Civil Rights"],
    website: "https://ag.nv.gov",
    socialHandles: { x: "AaronDFordNV", facebook: "AaronDFordNV", instagram: "aaronfordnv" },
    phone: "(702) 486-3420",
  },
  {
    id: "aguilar",
    name: "Francisco \"Cisco\" Aguilar",
    title: "Secretary of State",
    party: "Democrat",
    office: "Nevada Secretary of State",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://www.nvsos.gov/sos/images/SOS-Official-Photo.jpg",
    bio: "Cisco Aguilar is Nevada's Secretary of State, taking office in 2023. He oversees elections, business filings, and securities regulation for the state.",
    keyIssues: ["Election Security", "Business Development", "Voter Access", "Government Transparency"],
    website: "https://www.nvsos.gov",
    socialHandles: { x: "nvabornsecofstate", facebook: "NVSecretaryofState" },
    phone: "(775) 684-5708",
  },
  {
    id: "conine",
    name: "Zach Conine",
    title: "State Treasurer",
    party: "Democrat",
    office: "Nevada State Treasurer",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://www.nevadatreasurer.gov/uploadedImages/treasurernvgov/content/Home/Features/Front%20Page%20Headshot.jpg",
    bio: "Zach Conine serves as Nevada's State Treasurer, managing state investments and financial programs. He focuses on college savings and fiscal transparency.",
    keyIssues: ["State Finance", "College Savings", "Fiscal Transparency", "Federal Policy"],
    website: "https://www.nevadatreasurer.gov",
    socialHandles: { x: "ZachConine", facebook: "NVTreasurer" },
    phone: "(702) 486-2025",
  },
  {
    id: "matthews",
    name: "Andy Matthews",
    title: "State Controller",
    party: "Republican",
    office: "Nevada State Controller",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://www.controller.nv.gov/siteassets/content/controllerinfo/andy-matthews-headshot.jpg",
    bio: "Andy Matthews is Nevada's 23rd State Controller, taking office in January 2023. A former state assemblyman and policy advocate, he focuses on fiscal responsibility, government transparency, and accountability.",
    keyIssues: ["Fiscal Responsibility", "Government Transparency", "Accountability", "Debt Management"],
    website: "https://controller.nv.gov",
    phone: "(775) 684-5750",
  },

  // ═══════════════════════════════════════════════════════
  // STATE — Nevada Senate Leadership
  // ═══════════════════════════════════════════════════════
  {
    id: "cannizzaro",
    name: "Nicole Cannizzaro",
    title: "State Senate Majority Leader",
    party: "Democrat",
    office: "Nevada Senate, District 6",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/cannizzaro.jpg",
    bio: "Nicole Cannizzaro serves as Nevada Senate Majority Leader. A Clark County prosecutor, she focuses on criminal justice, public safety, and education funding.",
    keyIssues: ["Criminal Justice", "Public Safety", "Education Funding", "Worker Protections"],
  },
  {
    id: "goicoechea",
    name: "Pete Goicoechea",
    title: "State Senate Minority Leader",
    party: "Republican",
    office: "Nevada Senate, District 19",
    region: "Rural Nevada",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/goicoechea.jpg",
    bio: "Pete Goicoechea serves as Nevada Senate Minority Leader, representing rural Nevada. A rancher, he focuses on water rights, mining, and public lands.",
    keyIssues: ["Water Rights", "Mining", "Public Lands", "Agriculture"],
  },
  {
    id: "buck",
    name: "Carrie Ann Buck",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 5",
    region: "Henderson / Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/buck.jpg",
    bio: "Carrie Ann Buck represents Nevada Senate District 5 in the Henderson area. She focuses on education, school choice, and fiscal responsibility.",
    keyIssues: ["Education", "School Choice", "Fiscal Responsibility", "Public Safety"],
  },
  {
    id: "cruz-crawford",
    name: "Michelee \"Shelly\" Cruz-Crawford",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 1",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/cruz-crawford.jpg",
    bio: "Shelly Cruz-Crawford represents Nevada Senate District 1 in Clark County, focusing on community investment and healthcare access.",
    keyIssues: ["Healthcare", "Community Investment", "Education", "Housing"],
  },
  {
    id: "dondero-loop",
    name: "Chris Dondero Loop",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 8",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/donderoloop.jpg",
    bio: "Chris Dondero Loop represents Nevada Senate District 8, focusing on education, healthcare, and community development.",
    keyIssues: ["Education", "Healthcare", "Community Development", "Environment"],
  },
  {
    id: "donate",
    name: "Fabian Doñate",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 10",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/donate.jpg",
    bio: "Fabian Doñate represents Nevada Senate District 10, focusing on labor rights, immigration, and economic equity.",
    keyIssues: ["Labor Rights", "Immigration", "Economic Equity", "Healthcare"],
  },
  {
    id: "flores",
    name: "Edgar Flores",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 2",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/flores.jpg",
    bio: "Edgar Flores represents Nevada Senate District 2. An immigration attorney, he focuses on immigration reform, education, and criminal justice.",
    keyIssues: ["Immigration Reform", "Education", "Criminal Justice", "Civil Rights"],
  },
  {
    id: "hammond",
    name: "Scott Hammond",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 18",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/hammond.jpg",
    bio: "Scott Hammond represents Nevada Senate District 18, focusing on education reform, public safety, and fiscal responsibility.",
    keyIssues: ["Education Reform", "Public Safety", "Fiscal Responsibility", "Tax Policy"],
  },
  {
    id: "hansen-state",
    name: "Ira Hansen",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 14",
    region: "Washoe / Storey / Lyon",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/hansen.jpg",
    bio: "Ira Hansen represents Nevada Senate District 14 in the Washoe County area, focusing on small government, gun rights, and fiscal conservatism.",
    keyIssues: ["Gun Rights", "Small Government", "Tax Policy", "Property Rights"],
  },
  {
    id: "harris",
    name: "Dallas Harris",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 11",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/harris.jpg",
    bio: "Dallas Harris represents Nevada Senate District 11, focusing on energy policy, consumer protection, and government transparency.",
    keyIssues: ["Energy Policy", "Consumer Protection", "Government Transparency", "Technology"],
  },
  {
    id: "krasner",
    name: "Lisa Krasner",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 16",
    region: "Washoe County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/krasner.jpg",
    bio: "Lisa Krasner represents Nevada Senate District 16 in the Reno area, focusing on public safety, education, and property rights.",
    keyIssues: ["Public Safety", "Education", "Property Rights", "Fiscal Responsibility"],
  },
  {
    id: "neal",
    name: "Dina Neal",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 4",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/neal.jpg",
    bio: "Dina Neal represents Nevada Senate District 4 in North Las Vegas, focusing on economic development, criminal justice reform, and community investment.",
    keyIssues: ["Economic Development", "Criminal Justice Reform", "Community Investment", "Education"],
  },
  {
    id: "nguyen-duy",
    name: "Duy Nguyen",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 9",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/nguyen.jpg",
    bio: "Duy Nguyen represents Nevada Senate District 9, focusing on healthcare, small business, and veteran affairs.",
    keyIssues: ["Healthcare", "Small Business", "Veterans Affairs", "Education"],
  },
  {
    id: "ohrenschall",
    name: "James Ohrenschall",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 12",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/ohrenschall.jpg",
    bio: "James Ohrenschall represents Nevada Senate District 12, focusing on criminal justice reform, mental health, and consumer protection.",
    keyIssues: ["Criminal Justice Reform", "Mental Health", "Consumer Protection", "Civil Rights"],
  },
  {
    id: "pazina",
    name: "Jeff Pazina",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 20",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/pazina.jpg",
    bio: "Jeff Pazina represents Nevada Senate District 20 in Clark County, focusing on public safety, business development, and education.",
    keyIssues: ["Public Safety", "Business Development", "Education", "Tax Policy"],
  },
  {
    id: "scheible",
    name: "Melanie Scheible",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 9",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/scheible.jpg",
    bio: "Melanie Scheible represents parts of Clark County in the Nevada Senate, focusing on public safety, criminal justice, and domestic violence prevention.",
    keyIssues: ["Public Safety", "Criminal Justice", "Domestic Violence Prevention", "Education"],
  },
  {
    id: "seevers-gansert",
    name: "Heidi Seevers Gansert",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 15",
    region: "Washoe County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/seeversgansert.jpg",
    bio: "Heidi Seevers Gansert represents Nevada Senate District 15 in the Reno/Sparks area, focusing on economic development, education, and infrastructure.",
    keyIssues: ["Economic Development", "Education", "Infrastructure", "Technology"],
  },
  {
    id: "spearman",
    name: "Pat Spearman",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 3",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/spearman.jpg",
    bio: "Pat Spearman represents Nevada Senate District 3 in North Las Vegas. A retired Army colonel, she focuses on veterans' affairs, civil rights, and education.",
    keyIssues: ["Veterans Affairs", "Civil Rights", "Education", "Economic Equity"],
  },
  {
    id: "titus-robin",
    name: "Robin Titus",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 17",
    region: "Rural Nevada",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/titus.jpg",
    bio: "Robin Titus represents rural Nevada in the state Senate, focusing on healthcare, agriculture, and water rights as a physician and rancher.",
    keyIssues: ["Healthcare", "Agriculture", "Water Rights", "Rural Development"],
  },
  {
    id: "nguyen-rochelle",
    name: "Rochelle Nguyen",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 7",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/nguyenr.jpg",
    bio: "Rochelle Nguyen represents Nevada Senate District 7 in Clark County, focusing on criminal justice reform, healthcare, and consumer protection.",
    keyIssues: ["Criminal Justice Reform", "Healthcare", "Consumer Protection", "Housing"],
  },

  // ═══════════════════════════════════════════════════════
  // STATE — Nevada Assembly
  // ═══════════════════════════════════════════════════════
  {
    id: "anderson-assembly",
    name: "Lori Anderson",
    title: "Assemblywoman",
    party: "Republican",
    office: "Nevada Assembly, District 31",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/anderson.jpg",
    bio: "Lori Anderson represents Assembly District 31 in Clark County, focusing on education, public safety, and fiscal responsibility.",
    keyIssues: ["Education", "Public Safety", "Fiscal Responsibility", "Healthcare"],
  },
  {
    id: "backus",
    name: "Daniele Monroe-Moreno Backus",
    title: "Speaker of the Assembly",
    party: "Democrat",
    office: "Nevada Assembly, District 1",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/backus.jpg",
    bio: "Daniele Monroe-Moreno Backus serves as Speaker of the Nevada Assembly, representing District 1 in North Las Vegas. She focuses on public safety and community development.",
    keyIssues: ["Public Safety", "Community Development", "Education", "Veterans Affairs"],
  },
  {
    id: "bilbray-axelrod",
    name: "Shannon Bilbray-Axelrod",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 34",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/bilbray-axelrod.jpg",
    bio: "Shannon Bilbray-Axelrod represents Assembly District 34 in Clark County, focusing on education, healthcare, and child welfare.",
    keyIssues: ["Education", "Healthcare", "Child Welfare", "Community Services"],
  },
  {
    id: "brown-assembly",
    name: "Shea Backus Brown",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 37",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/brown.jpg",
    bio: "Shea Backus Brown represents Assembly District 37, focusing on legal reform, consumer protection, and education.",
    keyIssues: ["Legal Reform", "Consumer Protection", "Education", "Housing"],
  },
  {
    id: "carter",
    name: "C.H. Miller Carter",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 7",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/carter.jpg",
    bio: "C.H. Miller Carter represents Assembly District 7 in North Las Vegas, focusing on community investment and social equity.",
    keyIssues: ["Community Investment", "Social Equity", "Education", "Healthcare"],
  },
  {
    id: "cohen",
    name: "Lesley Cohen",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 29",
    region: "Henderson",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/cohen.jpg",
    bio: "Lesley Cohen represents Assembly District 29 in Henderson, focusing on consumer protection, judiciary issues, and education.",
    keyIssues: ["Consumer Protection", "Judiciary", "Education", "Public Safety"],
  },
  {
    id: "considine",
    name: "Skip Considine",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 20",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/considine.jpg",
    bio: "Skip Considine represents Assembly District 20 in Clark County, focusing on labor rights and economic development.",
    keyIssues: ["Labor Rights", "Economic Development", "Education", "Transportation"],
  },
  {
    id: "d-silva",
    name: "David \"DJ\" D'Silva",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 25",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/dsilva.jpg",
    bio: "DJ D'Silva represents Assembly District 25 in Clark County, focusing on business development, education, and technology.",
    keyIssues: ["Business Development", "Education", "Technology", "Community Services"],
  },
  {
    id: "dickman",
    name: "Jill Dickman",
    title: "Assemblywoman",
    party: "Republican",
    office: "Nevada Assembly, District 26",
    region: "Washoe County / Sparks",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/dickman.jpg",
    bio: "Jill Dickman represents Assembly District 26 in Sparks and eastern Washoe County, focusing on education, small business, and public safety.",
    keyIssues: ["Education", "Small Business", "Public Safety", "Fiscal Responsibility"],
  },
  {
    id: "duran",
    name: "Cecelia González Duran",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 11",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/duran.jpg",
    bio: "Cecelia González Duran represents Assembly District 11 in Clark County, focusing on immigration, education, and community development.",
    keyIssues: ["Immigration", "Education", "Community Development", "Healthcare"],
  },
  {
    id: "gallant",
    name: "Andy Gallant",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 23",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/gallant.jpg",
    bio: "Andy Gallant represents Assembly District 23, focusing on public safety, fiscal responsibility, and government reform.",
    keyIssues: ["Public Safety", "Fiscal Responsibility", "Government Reform", "Education"],
  },
  {
    id: "gonzalez",
    name: "David Gonzalez",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 16",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/gonzalez.jpg",
    bio: "David Gonzalez represents Assembly District 16 in Clark County, focusing on labor, education, and community services.",
    keyIssues: ["Labor Rights", "Education", "Community Services", "Healthcare"],
  },
  {
    id: "gray",
    name: "Gregory T. Gray",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 6",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/gray.jpg",
    bio: "Gregory T. Gray represents Assembly District 6 in North Las Vegas, focusing on criminal justice reform and community development.",
    keyIssues: ["Criminal Justice Reform", "Community Development", "Education", "Economic Equity"],
  },
  {
    id: "gorelow",
    name: "Venicia Considine Gorelow",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 35",
    region: "Henderson",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/gorelow.jpg",
    bio: "Venicia Considine Gorelow represents Assembly District 35 in Henderson, focusing on education, STEM, and economic development.",
    keyIssues: ["Education", "STEM", "Economic Development", "Community Services"],
  },
  {
    id: "gurr",
    name: "Greg Gurr",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 32",
    region: "Mesquite / Rural Clark",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/gurr.jpg",
    bio: "Greg Gurr represents Assembly District 32 covering Mesquite and rural Clark County, focusing on rural issues, agriculture, and water rights.",
    keyIssues: ["Rural Development", "Agriculture", "Water Rights", "Public Lands"],
  },
  {
    id: "hafen",
    name: "Gregory Hafen II",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 36",
    region: "Pahrump / Nye County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/hafen.jpg",
    bio: "Gregory Hafen II represents Assembly District 36 covering Pahrump and Nye County, focusing on water resources, property rights, and mining.",
    keyIssues: ["Water Resources", "Property Rights", "Mining", "Rural Development"],
  },
  {
    id: "hardy",
    name: "Melissa Hardy",
    title: "Assemblywoman",
    party: "Republican",
    office: "Nevada Assembly, District 22",
    region: "Henderson",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/hardy.jpg",
    bio: "Melissa Hardy represents Assembly District 22 in Henderson, focusing on education, healthcare, and public safety.",
    keyIssues: ["Education", "Healthcare", "Public Safety", "Fiscal Responsibility"],
  },
  {
    id: "hibbetts",
    name: "Ken Hibbetts",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 38",
    region: "Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/hibbetts.jpg",
    bio: "Ken Hibbetts represents Assembly District 38 in Las Vegas, focusing on public safety, fiscal responsibility, and small business.",
    keyIssues: ["Public Safety", "Fiscal Responsibility", "Small Business", "Education"],
  },
  {
    id: "jauregui",
    name: "Sandra Jauregui",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 41",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/jauregui.jpg",
    bio: "Sandra Jauregui represents Assembly District 41. A survivor of the 2017 Las Vegas shooting, she is a leading voice on gun violence prevention.",
    keyIssues: ["Gun Violence Prevention", "Public Safety", "Healthcare", "Education"],
  },
  {
    id: "kasama",
    name: "Heidi Kasama",
    title: "Assembly Minority Leader",
    party: "Republican",
    office: "Nevada Assembly, District 30",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/kasama.jpg",
    bio: "Heidi Kasama serves as Assembly Minority Leader, representing District 30. A businesswoman, she focuses on small business, economic growth, and education.",
    keyIssues: ["Small Business", "Economic Growth", "Education", "Public Safety"],
  },
  {
    id: "koenig",
    name: "Ken Koenig",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 21",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/koenig.jpg",
    bio: "Ken Koenig represents Assembly District 21 in Clark County, focusing on education, healthcare, and veterans' affairs.",
    keyIssues: ["Education", "Healthcare", "Veterans Affairs", "Government Efficiency"],
  },
  {
    id: "la-rue-hatch",
    name: "Tracy La Rue Hatch",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 19",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/laruehatch.jpg",
    bio: "Tracy La Rue Hatch represents Assembly District 19 in Clark County, focusing on social services, mental health, and community programs.",
    keyIssues: ["Social Services", "Mental Health", "Community Programs", "Education"],
  },
  {
    id: "lopez",
    name: "Selena Torres Lopez",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 3",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/lopez.jpg",
    bio: "Selena Torres Lopez represents Assembly District 3 in North Las Vegas, focusing on education, immigration, and healthcare access.",
    keyIssues: ["Education", "Immigration", "Healthcare Access", "Community Development"],
  },
  {
    id: "martinez",
    name: "Desiree Martinez",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 14",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/martinez.jpg",
    bio: "Desiree Martinez represents Assembly District 14 in Clark County, focusing on labor rights, education, and community engagement.",
    keyIssues: ["Labor Rights", "Education", "Community Engagement", "Healthcare"],
  },
  {
    id: "marzola",
    name: "Brittney Marzola",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 42",
    region: "Washoe County / Reno",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/marzola.jpg",
    bio: "Brittney Marzola represents Assembly District 42 in the Reno area, focusing on education, healthcare, and housing.",
    keyIssues: ["Education", "Healthcare", "Housing", "Economic Development"],
  },
  {
    id: "matheus",
    name: "Elaine Matheus",
    title: "Assemblywoman",
    party: "Republican",
    office: "Nevada Assembly, District 37",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/matheus.jpg",
    bio: "Elaine Matheus represents Assembly District 37 in Clark County, focusing on education, small business, and fiscal responsibility.",
    keyIssues: ["Education", "Small Business", "Fiscal Responsibility", "Public Safety"],
  },
  {
    id: "mcarthur",
    name: "Richard McArthur",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 4",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/mcarthur.jpg",
    bio: "Richard McArthur represents Assembly District 4 in North Las Vegas. He focuses on small government, tax reform, and public safety.",
    keyIssues: ["Small Government", "Tax Reform", "Public Safety", "Property Rights"],
  },
  {
    id: "mccurdy-assembly",
    name: "William McCurdy II",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 5",
    region: "Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/mccurdy.jpg",
    bio: "William McCurdy II represents Assembly District 5. He focuses on social equity, economic opportunity, and community engagement.",
    keyIssues: ["Social Equity", "Economic Opportunity", "Community Engagement", "Education"],
  },
  {
    id: "mosca",
    name: "Connie Munk Mosca",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 9",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/mosca.jpg",
    bio: "Connie Munk Mosca represents Assembly District 9 in Clark County, focusing on education, healthcare, and senior services.",
    keyIssues: ["Education", "Healthcare", "Senior Services", "Community Development"],
  },
  {
    id: "nguyen-assembly",
    name: "Tina Nguyen",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 12",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/nguyent.jpg",
    bio: "Tina Nguyen represents Assembly District 12 in Clark County, focusing on small business, healthcare, and education.",
    keyIssues: ["Small Business", "Healthcare", "Education", "Community Services"],
  },
  {
    id: "o-neill",
    name: "P.K. O'Neill",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 40",
    region: "Carson City / Douglas County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/oneill.jpg",
    bio: "P.K. O'Neill represents Assembly District 40 covering Carson City and parts of Douglas County. A retired law enforcement officer, he focuses on public safety.",
    keyIssues: ["Public Safety", "Veterans Affairs", "Fiscal Responsibility", "Rural Issues"],
  },
  {
    id: "peters",
    name: "Alexis Hansen Peters",
    title: "Assemblywoman",
    party: "Republican",
    office: "Nevada Assembly, District 33",
    region: "Elko / Rural Nevada",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/peters.jpg",
    bio: "Alexis Hansen Peters represents Assembly District 33 covering rural northeastern Nevada including Elko. She focuses on mining, agriculture, and water rights.",
    keyIssues: ["Mining", "Agriculture", "Water Rights", "Rural Development"],
  },
  {
    id: "roberts",
    name: "Sam Roberts",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 13",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/roberts.jpg",
    bio: "Sam Roberts represents Assembly District 13 in Clark County, focusing on education, community investment, and criminal justice reform.",
    keyIssues: ["Education", "Community Investment", "Criminal Justice Reform", "Housing"],
  },
  {
    id: "summers-armstrong-assembly",
    name: "Shondra Summers-Armstrong",
    title: "Assemblywoman",
    party: "Democrat",
    office: "Nevada Assembly, District 8",
    region: "Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/summersarmstrong.jpg",
    bio: "Shondra Summers-Armstrong represents Assembly District 8 in Las Vegas, focusing on community investment and social equity.",
    keyIssues: ["Community Investment", "Social Equity", "Education", "Public Safety"],
  },
  {
    id: "taylor",
    name: "Brittany Taylor",
    title: "Assemblywoman",
    party: "Republican",
    office: "Nevada Assembly, District 27",
    region: "Washoe County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/taylor.jpg",
    bio: "Brittany Taylor represents Assembly District 27 in Washoe County, focusing on education, public safety, and family issues.",
    keyIssues: ["Education", "Public Safety", "Family Issues", "Fiscal Responsibility"],
  },
  {
    id: "thomas",
    name: "Steve Thomas",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 24",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/thomas.jpg",
    bio: "Steve Thomas represents Assembly District 24 in Clark County, focusing on public safety, government efficiency, and tax reform.",
    keyIssues: ["Public Safety", "Government Efficiency", "Tax Reform", "Small Business"],
  },
  {
    id: "torres",
    name: "Selena Torres",
    title: "Assembly Majority Leader",
    party: "Democrat",
    office: "Nevada Assembly, District 10",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/torres.jpg",
    bio: "Selena Torres serves as Assembly Majority Leader, representing District 10 in Clark County. She focuses on education, immigration, and worker protections.",
    keyIssues: ["Education", "Immigration", "Worker Protections", "Healthcare"],
  },
  {
    id: "watts",
    name: "Howard Watts III",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 15",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/watts.jpg",
    bio: "Howard Watts III represents Assembly District 15 in Clark County. He focuses on clean energy, environmental protection, and government transparency.",
    keyIssues: ["Clean Energy", "Environment", "Government Transparency", "Technology"],
  },
  {
    id: "wheeler",
    name: "Jim Wheeler",
    title: "Assemblyman",
    party: "Republican",
    office: "Nevada Assembly, District 39",
    region: "Douglas / Lyon County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/wheeler.jpg",
    bio: "Jim Wheeler represents Assembly District 39 covering Douglas and Lyon counties. He focuses on gun rights, tax policy, and government accountability.",
    keyIssues: ["Gun Rights", "Tax Policy", "Government Accountability", "Property Rights"],
  },
  {
    id: "yeager",
    name: "Steve Yeager",
    title: "Assemblyman",
    party: "Democrat",
    office: "Nevada Assembly, District 17",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Assembly/photos/yeager.jpg",
    bio: "Steve Yeager represents Assembly District 17 in Clark County. A public defender, he focuses on criminal justice reform, education, and public safety.",
    keyIssues: ["Criminal Justice Reform", "Education", "Public Safety", "Worker Protections"],
  },

  // ═══════════════════════════════════════════════════════
  // COUNTY — Clark County Commission
  // ═══════════════════════════════════════════════════════
  {
    id: "naft",
    name: "Michael Naft",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District A",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:98ac59fb-cddc-4305-aeeb-ab35a3d45278/as/naft.jpg",
    bio: "Michael Naft serves as Clark County Commissioner for District A. He focuses on public safety, transportation, and community services in the southern Las Vegas valley.",
    keyIssues: ["Public Safety", "Transportation", "Community Services", "Infrastructure"],
    website: "https://www.clarkcountynv.gov/government/county_commissioners/district_a/index.php",
    socialHandles: { x: "MichaelNaft" },
  },
  {
    id: "kirkpatrick",
    name: "Marilyn Kirkpatrick",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District B",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:b5c9eed3-ba3e-4bad-980e-9cb8a022f8c2/as/kirkpatrick.jpg",
    bio: "Marilyn Kirkpatrick serves as Clark County Commissioner for District B. A former State Assembly Speaker, she focuses on economic development and infrastructure.",
    keyIssues: ["Economic Development", "Infrastructure", "Housing", "Public Lands"],
    website: "https://www.clarkcountynv.gov/government/county_commissioners/district_b/index.php",
  },
  {
    id: "becker",
    name: "April Becker",
    title: "County Commissioner",
    party: "Republican",
    office: "Clark County Commission, District C",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:9cb57239-6bb9-4981-a1b4-90a7b41116b2/as/becker.jpg",
    bio: "April Becker serves as Clark County Commissioner for District C. An attorney, she focuses on fiscal responsibility, public safety, and government transparency.",
    keyIssues: ["Fiscal Responsibility", "Public Safety", "Government Transparency", "Business Development"],
  },
  {
    id: "mccurdy",
    name: "William McCurdy II",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District D",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:9b9e1a78-b039-4c86-bebf-0b24ab683bb7/as/william-mccurdy-ii-waist-up-portrait-mod.jpg",
    bio: "William McCurdy II serves as Clark County Commissioner for District D. He focuses on social equity, economic development, and community engagement in the historic Westside and surrounding areas.",
    keyIssues: ["Social Equity", "Economic Development", "Community Engagement", "Education"],
  },
  {
    id: "segerblom",
    name: "Tick Segerblom",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District E",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:f8c00c05-5bce-421d-9c26-18c02bc02ea8/as/segerblom.jpg",
    bio: "Tick Segerblom serves as Clark County Commissioner for District E. A former state senator, he is known for championing cannabis legalization and progressive causes.",
    keyIssues: ["Cannabis Policy", "Progressive Reform", "Public Lands", "Arts & Culture"],
  },
  {
    id: "jones",
    name: "Justin Jones",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District F",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:34d0918c-6074-45d8-9606-dc43a3a0b220/as/jones.jpg",
    bio: "Justin Jones serves as Clark County Commissioner for District F, focusing on environmental issues, renewable energy, and community development.",
    keyIssues: ["Environment", "Renewable Energy", "Community Development", "Public Safety"],
  },
  {
    id: "gibson",
    name: "James B. Gibson",
    title: "County Commissioner (Chair)",
    party: "Democrat",
    office: "Clark County Commission, District G",
    region: "Henderson / Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:dea9b0ac-e96d-472f-a5c8-cd7fc896288d/as/gibson.jpg",
    bio: "Jim Gibson serves as Chair of the Clark County Commission for District G. A former Henderson mayor, he focuses on regional planning, transportation, and water conservation.",
    keyIssues: ["Regional Planning", "Transportation", "Water Conservation", "Economic Development"],
  },

  // ═══════════════════════════════════════════════════════
  // COUNTY — Washoe County Commission
  // ═══════════════════════════════════════════════════════
  {
    id: "herman",
    name: "Jeanne Herman",
    title: "County Commissioner",
    party: "Republican",
    office: "Washoe County Commission, District 5",
    region: "Washoe County",
    level: "county",
    imageUrl: "https://www.washoecounty.gov/bcc/files/images/herman_jeanne.jpg",
    bio: "Jeanne Herman serves as Washoe County Commissioner for District 5, representing the rural western portion of the county. She focuses on property rights, water, and rural issues.",
    keyIssues: ["Property Rights", "Water Rights", "Rural Development", "Government Transparency"],
  },
  {
    id: "clark-washoe",
    name: "Mike Clark",
    title: "County Commissioner",
    party: "Republican",
    office: "Washoe County Commission, District 3",
    region: "Washoe County",
    level: "county",
    imageUrl: "https://www.washoecounty.gov/bcc/files/images/commissioner-photos_0000_Mike-Clark_High-Res.jpg",
    bio: "Mike Clark serves as Washoe County Commissioner for District 3, focusing on fiscal responsibility, public safety, and infrastructure.",
    keyIssues: ["Fiscal Responsibility", "Public Safety", "Infrastructure", "Growth Management"],
  },
  {
    id: "hill",
    name: "Alexis Hill",
    title: "County Commissioner",
    party: "Democrat",
    office: "Washoe County Commission, District 1",
    region: "Washoe County / Incline Village",
    level: "county",
    imageUrl: "https://www.washoecounty.gov/bcc/files/images/alexis-hill.jpg",
    bio: "Alexis Hill serves as Washoe County Commissioner for District 1, representing Incline Village and surrounding areas. She focuses on wildfire prevention, housing, and the environment.",
    keyIssues: ["Wildfire Prevention", "Housing", "Environment", "Regional Planning"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of Las Vegas
  // ═══════════════════════════════════════════════════════
  {
    id: "berkley",
    name: "Shelley Berkley",
    title: "Mayor",
    party: "Democrat",
    office: "Mayor of Las Vegas",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/council/Mayor/Las_Vegas_Mayor_Shelley_Berkley_app_June-23-2025-600x800.jpg",
    bio: "Shelley Berkley serves as Mayor of Las Vegas. A former U.S. Representative, she focuses on downtown revitalization, tourism economy, and housing affordability.",
    keyIssues: ["Downtown Development", "Tourism Economy", "Housing", "Infrastructure"],
    website: "https://www.lasvegasnevada.gov/Government/Mayor",
    socialHandles: { x: "MayorBerkley", facebook: "MayorShelleyBerkley", instagram: "mayorberkley" },
    phone: "(702) 229-6241",
  },
  {
    id: "knudsen",
    name: "Brian Knudsen",
    title: "Mayor Pro Tem, Ward 1",
    party: "Democrat",
    office: "Las Vegas City Council, Ward 1",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/images/Knudsen-Headshot.jpg",
    bio: "Brian Knudsen serves as Mayor Pro Tem and Ward 1 Council Member for Las Vegas. He focuses on community development, public safety, and parks & recreation.",
    keyIssues: ["Community Development", "Public Safety", "Parks & Recreation", "Neighborhood Services"],
  },
  {
    id: "kelley",
    name: "Kara Kelley",
    title: "Councilwoman, Ward 2",
    party: "Nonpartisan",
    office: "Las Vegas City Council, Ward 2",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/images/Kara_Kelley-Sept-2025-600x800.jpg",
    bio: "Kara Kelley was appointed to the Las Vegas City Council Ward 2 seat in 2025 after Victoria Seaman's resignation. The former Vegas Chamber CEO focuses on business development and economic growth.",
    keyIssues: ["Business Development", "Economic Growth", "Tourism", "Community Services"],
  },
  {
    id: "diaz",
    name: "Olivia Diaz",
    title: "Councilwoman, Ward 3",
    party: "Democrat",
    office: "Las Vegas City Council, Ward 3",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/images/Olivia_Diaz_Portrait-600x400.jpg",
    bio: "Olivia Diaz represents Ward 3 on the Las Vegas City Council. A former educator, she focuses on education, community engagement, and neighborhood revitalization.",
    keyIssues: ["Education", "Community Engagement", "Neighborhood Revitalization", "Cultural Programs"],
  },
  {
    id: "allen-palenske",
    name: "Francis Allen-Palenske",
    title: "Councilwoman, Ward 4",
    party: "Nonpartisan",
    office: "Las Vegas City Council, Ward 4",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/council/Ward_4_2019/Francis_Allen-Palenske_Dec-2022-600x800.jpg",
    bio: "Francis Allen-Palenske represents Ward 4 on the Las Vegas City Council, focusing on public safety, infrastructure, and community services.",
    keyIssues: ["Public Safety", "Infrastructure", "Community Services", "Transportation"],
  },
  {
    id: "summers-armstrong",
    name: "Shondra Summers-Armstrong",
    title: "Councilwoman, Ward 5",
    party: "Democrat",
    office: "Las Vegas City Council, Ward 5",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/images/Shondra_Summers-Armstrong-2024-600x800.jpg",
    bio: "Shondra Summers-Armstrong represents Ward 5 on the Las Vegas City Council, focusing on community investment, housing equity, and economic opportunity.",
    keyIssues: ["Community Investment", "Housing Equity", "Economic Opportunity", "Public Safety"],
  },
  {
    id: "brune",
    name: "Nancy E. Brune",
    title: "Councilwoman, Ward 6",
    party: "Nonpartisan",
    office: "Las Vegas City Council, Ward 6",
    region: "Las Vegas",
    level: "local",
    imageUrl: "https://sawebfilesprod001.blob.core.windows.net/images/Nancy_Brune%2025%20RGB.jpg",
    bio: "Nancy Brune represents Ward 6 on the Las Vegas City Council. A policy researcher, she focuses on education, economic development, and evidence-based governance.",
    keyIssues: ["Education", "Economic Development", "Evidence-Based Policy", "Public Safety"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of Henderson
  // ═══════════════════════════════════════════════════════
  {
    id: "romero",
    name: "Michelle Romero",
    title: "Mayor",
    party: "Nonpartisan",
    office: "Mayor of Henderson",
    region: "Henderson",
    level: "local",
    imageUrl: "https://www.cityofhenderson.com/home/showpublishedimage/12393/637768773816530000",
    bio: "Michelle Romero was elected Mayor of Henderson in 2022. She previously served on Henderson City Council and focuses on growth management, public safety, and quality of life.",
    keyIssues: ["Growth Management", "Public Safety", "Quality of Life", "Economic Development"],
    website: "https://www.cityofhenderson.com/government/mayor-and-council/mayor",
  },
  {
    id: "larson",
    name: "Dr. Monica Larson",
    title: "Councilwoman, Ward II",
    party: "Nonpartisan",
    office: "Henderson City Council, Ward II",
    region: "Henderson",
    level: "local",
    imageUrl: "https://www.cityofhenderson.com/home/showpublishedimage/15075/638735860460130000",
    bio: "Dr. Monica Larson was elected in 2024, becoming the first Black councilmember in Henderson's history. She focuses on community engagement and inclusive governance.",
    keyIssues: ["Community Engagement", "Inclusive Governance", "Education", "Public Safety"],
  },
  {
    id: "stewart",
    name: "Dan H. Stewart",
    title: "Councilman, Ward IV",
    party: "Nonpartisan",
    office: "Henderson City Council, Ward IV",
    region: "Henderson",
    level: "local",
    imageUrl: "https://www.cityofhenderson.com/home/showpublishedimage/11979/638880869602000000",
    bio: "Dan Stewart is a fourth-generation Nevadan serving on Henderson City Council. He has a background in engineering, real estate, and public service.",
    keyIssues: ["Infrastructure", "Economic Development", "Public Safety", "Community Planning"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of North Las Vegas
  // ═══════════════════════════════════════════════════════
  {
    id: "goynes-brown",
    name: "Pamela Goynes-Brown",
    title: "Mayor",
    party: "Democrat",
    office: "Mayor of North Las Vegas",
    region: "North Las Vegas",
    level: "local",
    imageUrl: "https://www.cityofnorthlasvegas.com/home/showpublishedimage/1640/638101406303930000",
    bio: "Pamela Goynes-Brown is the Mayor of North Las Vegas. A former councilwoman, she focuses on economic development, community investment, and infrastructure modernization.",
    keyIssues: ["Economic Development", "Community Investment", "Infrastructure", "Public Safety"],
    website: "https://www.cityofnorthlasvegas.com/government/mayor",
  },
  {
    id: "barron",
    name: "Isaac Barron",
    title: "Councilman, Ward 1",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 1",
    region: "North Las Vegas",
    level: "local",
    imageUrl: "https://www.cityofnorthlasvegas.com/home/showpublishedimage/1434/638100711590430000",
    bio: "Isaac Barron serves as North Las Vegas City Councilman for Ward 1, focusing on community engagement, education, and neighborhood improvement.",
    keyIssues: ["Community Engagement", "Education", "Neighborhood Improvement", "Youth Programs"],
  },
  {
    id: "garcia-anderson",
    name: "Ruth Garcia-Anderson",
    title: "Councilwoman, Ward 2",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 2",
    region: "North Las Vegas",
    level: "local",
    imageUrl: "https://www.cityofnorthlasvegas.com/home/showpublishedimage/1432/638100711577630000",
    bio: "Ruth Garcia-Anderson serves as North Las Vegas City Councilwoman for Ward 2, focusing on community services and public safety.",
    keyIssues: ["Community Services", "Public Safety", "Infrastructure", "Education"],
  },
  {
    id: "black",
    name: "Scott Black",
    title: "Councilman, Ward 3",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 3",
    region: "North Las Vegas",
    level: "local",
    imageUrl: "https://www.cityofnorthlasvegas.com/home/showpublishedimage/1436/638100711601830000",
    bio: "Scott Black serves as North Las Vegas City Councilman for Ward 3, focusing on economic growth and community development.",
    keyIssues: ["Economic Growth", "Community Development", "Public Safety", "Infrastructure"],
  },
  {
    id: "cherchio",
    name: "Richard Cherchio",
    title: "Councilman, Ward 4",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 4",
    region: "North Las Vegas",
    level: "local",
    imageUrl: "https://www.cityofnorthlasvegas.com/home/showpublishedimage/1438/638100711619500000",
    bio: "Richard Cherchio serves as North Las Vegas City Councilman for Ward 4, focusing on veterans' affairs, public safety, and community services.",
    keyIssues: ["Veterans Affairs", "Public Safety", "Community Services", "Infrastructure"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of Reno & Sparks
  // ═══════════════════════════════════════════════════════
  {
    id: "schieve",
    name: "Hillary Schieve",
    title: "Mayor",
    party: "Independent",
    office: "Mayor of Reno",
    region: "Reno",
    level: "local",
    imageUrl: "https://www.reno.gov/home/showpublishedimage/20013/638856713593970000",
    bio: "Hillary Schieve has served as Mayor of Reno since 2014. She focuses on economic diversification, homelessness, and downtown revitalization. She is term-limited in 2026.",
    keyIssues: ["Economic Diversification", "Homelessness", "Downtown Revitalization", "Technology"],
    website: "https://www.reno.gov/government/mayor",
    socialHandles: { x: "MayorSchieve", facebook: "MayorSchieve", instagram: "hillaryschieve" },
  },
  {
    id: "lawson",
    name: "Ed Lawson",
    title: "Mayor",
    party: "Republican",
    office: "Mayor of Sparks",
    region: "Sparks",
    level: "local",
    imageUrl: "https://www.cityofsparks.us/your_government/departments/maps_and_gis/community_maps/ward_maps/images/Ed_Lawson_2024_Headshot_8x10_crop2.jpg",
    bio: "Ed Lawson has served as Mayor of Sparks since 2020 and on the city council since 2010. He focuses on managing rapid growth, infrastructure, and public safety.",
    keyIssues: ["Growth Management", "Infrastructure", "Public Safety", "Budget"],
    website: "https://www.cityofsparks.us/government/mayor-and-city-council/mayor/",
  },
];
