export interface Politician {
  id: string;
  name: string;
  title: string;
  party: "Democrat" | "Republican" | "Independent" | "Nonpartisan";
  office: string;
  region: string;
  level: "federal" | "state" | "county" | "local";
  imageUrl?: string;
  bio: string;
  keyIssues: string[];
  socialHandles?: {
    x?: string;
  };
}

export const nevadaPoliticians: Politician[] = [
  // ═══════════════════════════════════════════════════════
  // FEDERAL — U.S. Senators
  // ═══════════════════════════════════════════════════════
  {
    id: "cortez-masto",
    name: "Catherine Cortez Masto",
    title: "U.S. Senator",
    party: "Democrat",
    office: "U.S. Senate",
    region: "State of Nevada",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/C/C001113.jpg",
    bio: "Catherine Cortez Masto is the senior U.S. Senator from Nevada, first elected in 2016. She is the first Latina elected to the U.S. Senate and focuses on immigration, healthcare, and clean energy.",
    keyIssues: ["Immigration Reform", "Healthcare", "Clean Energy", "Public Lands"],
    socialHandles: { x: "SenCortezMasto" },
  },
  {
    id: "rosen",
    name: "Jacky Rosen",
    title: "U.S. Senator",
    party: "Democrat",
    office: "U.S. Senate",
    region: "State of Nevada",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/R/R000608.jpg",
    bio: "Jacky Rosen is the junior U.S. Senator from Nevada, elected in 2018 and re-elected in 2024. A former computer programmer, she champions technology, veterans' issues, and workforce development.",
    keyIssues: ["Technology", "Veterans Affairs", "Workforce Development", "Small Business"],
    socialHandles: { x: "SenJackyRosen" },
  },

  // ═══════════════════════════════════════════════════════
  // FEDERAL — U.S. Representatives
  // ═══════════════════════════════════════════════════════
  {
    id: "titus",
    name: "Dina Titus",
    title: "U.S. Representative",
    party: "Democrat",
    office: "U.S. House (NV-1)",
    region: "Central Las Vegas",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/T/T000468.jpg",
    bio: "Dina Titus represents Nevada's 1st Congressional District covering central Las Vegas, including the Strip. A former political science professor, she focuses on tourism, transportation, and veterans' affairs.",
    keyIssues: ["Tourism", "Transportation", "Veterans Affairs", "Foreign Affairs"],
    socialHandles: { x: "RepDinaTitus" },
  },
  {
    id: "amodei",
    name: "Mark Amodei",
    title: "U.S. Representative",
    party: "Republican",
    office: "U.S. House (NV-2)",
    region: "Northern Nevada / Reno",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/A/A000369.jpg",
    bio: "Mark Amodei represents Nevada's 2nd Congressional District covering Reno and rural northern Nevada. He focuses on public lands, mining, and fiscal responsibility.",
    keyIssues: ["Public Lands", "Mining", "Fiscal Responsibility", "Water Rights"],
    socialHandles: { x: "MarkAmodeiNV2" },
  },
  {
    id: "lee",
    name: "Susie Lee",
    title: "U.S. Representative",
    party: "Democrat",
    office: "U.S. House (NV-3)",
    region: "Southern Nevada / Henderson",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/L/L000590.jpg",
    bio: "Susie Lee represents Nevada's 3rd Congressional District covering suburban Las Vegas and Henderson. She focuses on education, healthcare, and environmental protection.",
    keyIssues: ["Education", "Healthcare", "Environment", "Gun Safety"],
    socialHandles: { x: "RepSusieLee" },
  },
  {
    id: "horsford",
    name: "Steven Horsford",
    title: "U.S. Representative",
    party: "Democrat",
    office: "U.S. House (NV-4)",
    region: "North Las Vegas / Rural Nevada",
    level: "federal",
    imageUrl: "https://bioguide.congress.gov/bioguide/photo/H/H001066.jpg",
    bio: "Steven Horsford represents Nevada's 4th Congressional District. He focuses on economic equity, labor rights, and community investment in underserved areas.",
    keyIssues: ["Labor Rights", "Economic Equity", "Community Investment", "Healthcare Access"],
    socialHandles: { x: "RepHorsford" },
  },

  // ═══════════════════════════════════════════════════════
  // STATE — Constitutional Officers
  // ═══════════════════════════════════════════════════════
  {
    id: "lombardo",
    name: "Joe Lombardo",
    title: "Governor",
    party: "Republican",
    office: "Governor of Nevada",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://gov.nv.gov/wp-content/uploads/2024/02/jl-headshot-1-scaled.jpg",
    bio: "Joe Lombardo is the 31st Governor of Nevada, having taken office in January 2023. A former Clark County Sheriff, he focuses on public safety, economic growth, and education reform.",
    keyIssues: ["Public Safety", "Economic Development", "Education", "Water Conservation"],
    socialHandles: { x: "JoeLombardoNV" },
  },
  {
    id: "anthony",
    name: "Stavros Anthony",
    title: "Lieutenant Governor",
    party: "Republican",
    office: "Lt. Governor of Nevada",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://ltgov.nv.gov/wp-content/uploads/2023/01/stavros-anthony-headshot.jpg",
    bio: "Stavros Anthony is the Lieutenant Governor of Nevada. A former Las Vegas City Councilman and UNLV professor, he presides over the Nevada Senate and chairs the Nevada Commission on Tourism.",
    keyIssues: ["Tourism", "Economic Development", "Small Business", "Veterans"],
    socialHandles: { x: "prior_stavros" },
  },
  {
    id: "ford",
    name: "Aaron D. Ford",
    title: "Attorney General",
    party: "Democrat",
    office: "Nevada Attorney General",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://ag.nv.gov/wp-content/uploads/2024/09/AGFord_Official-scaled.jpg",
    bio: "Aaron D. Ford is Nevada's 34th Attorney General, taking office in 2019. He focuses on consumer protection, criminal justice reform, and protecting Nevada's elections.",
    keyIssues: ["Consumer Protection", "Criminal Justice Reform", "Election Integrity", "Civil Rights"],
    socialHandles: { x: "AaronDFordNV" },
  },
  {
    id: "aguilar",
    name: "Francisco \"Cisco\" Aguilar",
    title: "Secretary of State",
    party: "Democrat",
    office: "Nevada Secretary of State",
    region: "State of Nevada",
    level: "state",
    imageUrl: "https://www.nvsos.gov/sos/images/SOS-Official-Photo.jpg",
    bio: "Cisco Aguilar is Nevada's Secretary of State, taking office in 2023. He oversees elections, business filings, and securities regulation for the state.",
    keyIssues: ["Election Security", "Business Development", "Voter Access", "Government Transparency"],
    socialHandles: { x: "nvabornsecofstate" },
  },
  {
    id: "conine",
    name: "Zach Conine",
    title: "State Treasurer",
    party: "Democrat",
    office: "Nevada State Treasurer",
    region: "State of Nevada",
    level: "state",
    bio: "Zach Conine serves as Nevada's State Treasurer, managing state investments and financial programs. He focuses on college savings and fiscal transparency.",
    keyIssues: ["State Finance", "College Savings", "Fiscal Transparency", "Federal Policy"],
    socialHandles: { x: "ZachConine" },
  },
  {
    id: "marshall",
    name: "Kate Marshall",
    title: "State Controller",
    party: "Democrat",
    office: "Nevada State Controller",
    region: "State of Nevada",
    level: "state",
    bio: "Kate Marshall serves as Nevada's State Controller, responsible for state payments, debt collection, and financial reporting.",
    keyIssues: ["State Finance", "Government Accountability", "Fiscal Transparency", "Debt Management"],
  },

  // ═══════════════════════════════════════════════════════
  // STATE — Nevada Senate Leadership
  // ═══════════════════════════════════════════════════════
  {
    id: "cannizzaro",
    name: "Nicole Cannizzaro",
    title: "State Senate Majority Leader",
    party: "Democrat",
    office: "Nevada Senate, District 6",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/cannizzaro.jpg",
    bio: "Nicole Cannizzaro serves as Nevada Senate Majority Leader. A Clark County prosecutor, she focuses on criminal justice, public safety, and education funding.",
    keyIssues: ["Criminal Justice", "Public Safety", "Education Funding", "Worker Protections"],
  },
  {
    id: "goicoechea",
    name: "Pete Goicoechea",
    title: "State Senate Minority Leader",
    party: "Republican",
    office: "Nevada Senate, District 19",
    region: "Rural Nevada",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/goicoechea.jpg",
    bio: "Pete Goicoechea serves as Nevada Senate Minority Leader, representing rural Nevada. A rancher, he focuses on water rights, mining, and public lands.",
    keyIssues: ["Water Rights", "Mining", "Public Lands", "Agriculture"],
  },
  {
    id: "buck",
    name: "Carrie Ann Buck",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 5",
    region: "Henderson / Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/buck.jpg",
    bio: "Carrie Ann Buck represents Nevada Senate District 5 in the Henderson area. She focuses on education, school choice, and fiscal responsibility.",
    keyIssues: ["Education", "School Choice", "Fiscal Responsibility", "Public Safety"],
  },
  {
    id: "cruz-crawford",
    name: "Michelee \"Shelly\" Cruz-Crawford",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 1",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/cruz-crawford.jpg",
    bio: "Shelly Cruz-Crawford represents Nevada Senate District 1 in Clark County, focusing on community investment and healthcare access.",
    keyIssues: ["Healthcare", "Community Investment", "Education", "Housing"],
  },
  {
    id: "dondero-loop",
    name: "Chris Dondero Loop",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 8",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/donderoloop.jpg",
    bio: "Chris Dondero Loop represents Nevada Senate District 8, focusing on education, healthcare, and community development.",
    keyIssues: ["Education", "Healthcare", "Community Development", "Environment"],
  },
  {
    id: "donate",
    name: "Fabian Doñate",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 10",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/donate.jpg",
    bio: "Fabian Doñate represents Nevada Senate District 10, focusing on labor rights, immigration, and economic equity.",
    keyIssues: ["Labor Rights", "Immigration", "Economic Equity", "Healthcare"],
  },
  {
    id: "flores",
    name: "Edgar Flores",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 2",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/flores.jpg",
    bio: "Edgar Flores represents Nevada Senate District 2. An immigration attorney, he focuses on immigration reform, education, and criminal justice.",
    keyIssues: ["Immigration Reform", "Education", "Criminal Justice", "Civil Rights"],
  },
  {
    id: "hammond",
    name: "Scott Hammond",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 18",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/hammond.jpg",
    bio: "Scott Hammond represents Nevada Senate District 18, focusing on education reform, public safety, and fiscal responsibility.",
    keyIssues: ["Education Reform", "Public Safety", "Fiscal Responsibility", "Tax Policy"],
  },
  {
    id: "hansen-state",
    name: "Ira Hansen",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 14",
    region: "Washoe / Storey / Lyon",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/hansen.jpg",
    bio: "Ira Hansen represents Nevada Senate District 14 in the Washoe County area, focusing on small government, gun rights, and fiscal conservatism.",
    keyIssues: ["Gun Rights", "Small Government", "Tax Policy", "Property Rights"],
  },
  {
    id: "harris",
    name: "Dallas Harris",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 11",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/harris.jpg",
    bio: "Dallas Harris represents Nevada Senate District 11, focusing on energy policy, consumer protection, and government transparency.",
    keyIssues: ["Energy Policy", "Consumer Protection", "Government Transparency", "Technology"],
  },
  {
    id: "krasner",
    name: "Lisa Krasner",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 16",
    region: "Washoe County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/krasner.jpg",
    bio: "Lisa Krasner represents Nevada Senate District 16 in the Reno area, focusing on public safety, education, and property rights.",
    keyIssues: ["Public Safety", "Education", "Property Rights", "Fiscal Responsibility"],
  },
  {
    id: "neal",
    name: "Dina Neal",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 4",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/neal.jpg",
    bio: "Dina Neal represents Nevada Senate District 4 in North Las Vegas, focusing on economic development, criminal justice reform, and community investment.",
    keyIssues: ["Economic Development", "Criminal Justice Reform", "Community Investment", "Education"],
  },
  {
    id: "nguyen-duy",
    name: "Duy Nguyen",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 9",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/nguyen.jpg",
    bio: "Duy Nguyen represents Nevada Senate District 9, focusing on healthcare, small business, and veteran affairs.",
    keyIssues: ["Healthcare", "Small Business", "Veterans Affairs", "Education"],
  },
  {
    id: "ohrenschall",
    name: "James Ohrenschall",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 12",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/ohrenschall.jpg",
    bio: "James Ohrenschall represents Nevada Senate District 12, focusing on criminal justice reform, mental health, and consumer protection.",
    keyIssues: ["Criminal Justice Reform", "Mental Health", "Consumer Protection", "Civil Rights"],
  },
  {
    id: "pazina",
    name: "Jeff Pazina",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 20",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/pazina.jpg",
    bio: "Jeff Pazina represents Nevada Senate District 20 in Clark County, focusing on public safety, business development, and education.",
    keyIssues: ["Public Safety", "Business Development", "Education", "Tax Policy"],
  },
  {
    id: "scheible",
    name: "Melanie Scheible",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 9",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/scheible.jpg",
    bio: "Melanie Scheible represents parts of Clark County in the Nevada Senate, focusing on public safety, criminal justice, and domestic violence prevention.",
    keyIssues: ["Public Safety", "Criminal Justice", "Domestic Violence Prevention", "Education"],
  },
  {
    id: "seevers-gansert",
    name: "Heidi Seevers Gansert",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 15",
    region: "Washoe County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/seeversgansert.jpg",
    bio: "Heidi Seevers Gansert represents Nevada Senate District 15 in the Reno/Sparks area, focusing on economic development, education, and infrastructure.",
    keyIssues: ["Economic Development", "Education", "Infrastructure", "Technology"],
  },
  {
    id: "spearman",
    name: "Pat Spearman",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 3",
    region: "North Las Vegas",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/spearman.jpg",
    bio: "Pat Spearman represents Nevada Senate District 3 in North Las Vegas. A retired Army colonel, she focuses on veterans' affairs, civil rights, and education.",
    keyIssues: ["Veterans Affairs", "Civil Rights", "Education", "Economic Equity"],
  },
  {
    id: "titus-robin",
    name: "Robin Titus",
    title: "State Senator",
    party: "Republican",
    office: "Nevada Senate, District 17",
    region: "Rural Nevada",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/titus.jpg",
    bio: "Robin Titus represents rural Nevada in the state Senate, focusing on healthcare, agriculture, and water rights as a physician and rancher.",
    keyIssues: ["Healthcare", "Agriculture", "Water Rights", "Rural Development"],
  },
  {
    id: "nguyen-rochelle",
    name: "Rochelle Nguyen",
    title: "State Senator",
    party: "Democrat",
    office: "Nevada Senate, District 7",
    region: "Clark County",
    level: "state",
    imageUrl: "https://www.leg.state.nv.us/Session/83rd2025/Legislators/Senators/photos/nguyenr.jpg",
    bio: "Rochelle Nguyen represents Nevada Senate District 7 in Clark County, focusing on criminal justice reform, healthcare, and consumer protection.",
    keyIssues: ["Criminal Justice Reform", "Healthcare", "Consumer Protection", "Housing"],
  },

  // ═══════════════════════════════════════════════════════
  // COUNTY — Clark County Commission
  // ═══════════════════════════════════════════════════════
  {
    id: "naft",
    name: "Michael Naft",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District A",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:98ac59fb-cddc-4305-aeeb-ab35a3d45278/as/naft.jpg",
    bio: "Michael Naft serves as Clark County Commissioner for District A. He focuses on public safety, transportation, and community services in the southern Las Vegas valley.",
    keyIssues: ["Public Safety", "Transportation", "Community Services", "Infrastructure"],
  },
  {
    id: "kirkpatrick",
    name: "Marilyn Kirkpatrick",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District B",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:b5c9eed3-ba3e-4bad-980e-9cb8a022f8c2/as/kirkpatrick.jpg",
    bio: "Marilyn Kirkpatrick serves as Clark County Commissioner for District B. A former State Assembly Speaker, she focuses on economic development and infrastructure.",
    keyIssues: ["Economic Development", "Infrastructure", "Housing", "Public Lands"],
  },
  {
    id: "becker",
    name: "April Becker",
    title: "County Commissioner",
    party: "Republican",
    office: "Clark County Commission, District C",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:9cb57239-6bb9-4981-a1b4-90a7b41116b2/as/becker.jpg",
    bio: "April Becker serves as Clark County Commissioner for District C. An attorney, she focuses on fiscal responsibility, public safety, and government transparency.",
    keyIssues: ["Fiscal Responsibility", "Public Safety", "Government Transparency", "Business Development"],
  },
  {
    id: "mccurdy",
    name: "William McCurdy II",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District D",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:9b9e1a78-b039-4c86-bebf-0b24ab683bb7/as/william-mccurdy-ii-waist-up-portrait-mod.jpg",
    bio: "William McCurdy II serves as Clark County Commissioner for District D. He focuses on social equity, economic development, and community engagement in the historic Westside and surrounding areas.",
    keyIssues: ["Social Equity", "Economic Development", "Community Engagement", "Education"],
  },
  {
    id: "segerblom",
    name: "Tick Segerblom",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District E",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:f8c00c05-5bce-421d-9c26-18c02bc02ea8/as/segerblom.jpg",
    bio: "Tick Segerblom serves as Clark County Commissioner for District E. A former state senator, he is known for championing cannabis legalization and progressive causes.",
    keyIssues: ["Cannabis Policy", "Progressive Reform", "Public Lands", "Arts & Culture"],
  },
  {
    id: "jones",
    name: "Justin Jones",
    title: "County Commissioner",
    party: "Democrat",
    office: "Clark County Commission, District F",
    region: "Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:34d0918c-6074-45d8-9606-dc43a3a0b220/as/jones.jpg",
    bio: "Justin Jones serves as Clark County Commissioner for District F, focusing on environmental issues, renewable energy, and community development.",
    keyIssues: ["Environment", "Renewable Energy", "Community Development", "Public Safety"],
  },
  {
    id: "gibson",
    name: "James B. Gibson",
    title: "County Commissioner (Chair)",
    party: "Democrat",
    office: "Clark County Commission, District G",
    region: "Henderson / Clark County",
    level: "county",
    imageUrl: "https://www.clarkcountynv.gov/adobe/assets/urn:aaid:aem:dea9b0ac-e96d-472f-a5c8-cd7fc896288d/as/gibson.jpg",
    bio: "Jim Gibson serves as Chair of the Clark County Commission for District G. A former Henderson mayor, he focuses on regional planning, transportation, and water conservation.",
    keyIssues: ["Regional Planning", "Transportation", "Water Conservation", "Economic Development"],
  },

  // ═══════════════════════════════════════════════════════
  // COUNTY — Washoe County Commission
  // ═══════════════════════════════════════════════════════
  {
    id: "herman",
    name: "Jeanne Herman",
    title: "County Commissioner",
    party: "Republican",
    office: "Washoe County Commission, District 5",
    region: "Washoe County",
    level: "county",
    bio: "Jeanne Herman serves as Washoe County Commissioner for District 5, representing the rural western portion of the county. She focuses on property rights, water, and rural issues.",
    keyIssues: ["Property Rights", "Water Rights", "Rural Development", "Government Transparency"],
  },
  {
    id: "clark-washoe",
    name: "Mike Clark",
    title: "County Commissioner",
    party: "Republican",
    office: "Washoe County Commission, District 3",
    region: "Washoe County",
    level: "county",
    bio: "Mike Clark serves as Washoe County Commissioner for District 3, focusing on fiscal responsibility, public safety, and infrastructure.",
    keyIssues: ["Fiscal Responsibility", "Public Safety", "Infrastructure", "Growth Management"],
  },
  {
    id: "hill",
    name: "Alexis Hill",
    title: "County Commissioner",
    party: "Democrat",
    office: "Washoe County Commission, District 1",
    region: "Washoe County / Incline Village",
    level: "county",
    bio: "Alexis Hill serves as Washoe County Commissioner for District 1, representing Incline Village and surrounding areas. She focuses on wildfire prevention, housing, and the environment.",
    keyIssues: ["Wildfire Prevention", "Housing", "Environment", "Regional Planning"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of Las Vegas
  // ═══════════════════════════════════════════════════════
  {
    id: "berkley",
    name: "Shelley Berkley",
    title: "Mayor",
    party: "Democrat",
    office: "Mayor of Las Vegas",
    region: "Las Vegas",
    level: "local",
    bio: "Shelley Berkley serves as Mayor of Las Vegas. A former U.S. Representative, she focuses on downtown revitalization, tourism economy, and housing affordability.",
    keyIssues: ["Downtown Development", "Tourism Economy", "Housing", "Infrastructure"],
    socialHandles: { x: "MayorBerkley" },
  },
  {
    id: "knudsen",
    name: "Brian Knudsen",
    title: "Mayor Pro Tem, Ward 1",
    party: "Democrat",
    office: "Las Vegas City Council, Ward 1",
    region: "Las Vegas",
    level: "local",
    bio: "Brian Knudsen serves as Mayor Pro Tem and Ward 1 Council Member for Las Vegas. He focuses on community development, public safety, and parks & recreation.",
    keyIssues: ["Community Development", "Public Safety", "Parks & Recreation", "Neighborhood Services"],
  },
  {
    id: "kelley",
    name: "Kara Kelley",
    title: "Councilwoman, Ward 2",
    party: "Nonpartisan",
    office: "Las Vegas City Council, Ward 2",
    region: "Las Vegas",
    level: "local",
    bio: "Kara Kelley was appointed to the Las Vegas City Council Ward 2 seat in 2025 after Victoria Seaman's resignation. The former Vegas Chamber CEO focuses on business development and economic growth.",
    keyIssues: ["Business Development", "Economic Growth", "Tourism", "Community Services"],
  },
  {
    id: "diaz",
    name: "Olivia Diaz",
    title: "Councilwoman, Ward 3",
    party: "Democrat",
    office: "Las Vegas City Council, Ward 3",
    region: "Las Vegas",
    level: "local",
    bio: "Olivia Diaz represents Ward 3 on the Las Vegas City Council. A former educator, she focuses on education, community engagement, and neighborhood revitalization.",
    keyIssues: ["Education", "Community Engagement", "Neighborhood Revitalization", "Cultural Programs"],
  },
  {
    id: "allen-palenske",
    name: "Francis Allen-Palenske",
    title: "Councilwoman, Ward 4",
    party: "Nonpartisan",
    office: "Las Vegas City Council, Ward 4",
    region: "Las Vegas",
    level: "local",
    bio: "Francis Allen-Palenske represents Ward 4 on the Las Vegas City Council, focusing on public safety, infrastructure, and community services.",
    keyIssues: ["Public Safety", "Infrastructure", "Community Services", "Transportation"],
  },
  {
    id: "summers-armstrong",
    name: "Shondra Summers-Armstrong",
    title: "Councilwoman, Ward 5",
    party: "Democrat",
    office: "Las Vegas City Council, Ward 5",
    region: "Las Vegas",
    level: "local",
    bio: "Shondra Summers-Armstrong represents Ward 5 on the Las Vegas City Council, focusing on community investment, housing equity, and economic opportunity.",
    keyIssues: ["Community Investment", "Housing Equity", "Economic Opportunity", "Public Safety"],
  },
  {
    id: "brune",
    name: "Nancy E. Brune",
    title: "Councilwoman, Ward 6",
    party: "Nonpartisan",
    office: "Las Vegas City Council, Ward 6",
    region: "Las Vegas",
    level: "local",
    bio: "Nancy Brune represents Ward 6 on the Las Vegas City Council. A policy researcher, she focuses on education, economic development, and evidence-based governance.",
    keyIssues: ["Education", "Economic Development", "Evidence-Based Policy", "Public Safety"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of Henderson
  // ═══════════════════════════════════════════════════════
  {
    id: "romero",
    name: "Michelle Romero",
    title: "Mayor",
    party: "Nonpartisan",
    office: "Mayor of Henderson",
    region: "Henderson",
    level: "local",
    imageUrl: "https://www.cityofhenderson.com/home/showpublishedimage/12393/637768773816530000",
    bio: "Michelle Romero was elected Mayor of Henderson in 2022. She previously served on Henderson City Council and focuses on growth management, public safety, and quality of life.",
    keyIssues: ["Growth Management", "Public Safety", "Quality of Life", "Economic Development"],
  },
  {
    id: "larson",
    name: "Dr. Monica Larson",
    title: "Councilwoman, Ward II",
    party: "Nonpartisan",
    office: "Henderson City Council, Ward II",
    region: "Henderson",
    level: "local",
    bio: "Dr. Monica Larson was elected in 2024, becoming the first Black councilmember in Henderson's history. She focuses on community engagement and inclusive governance.",
    keyIssues: ["Community Engagement", "Inclusive Governance", "Education", "Public Safety"],
  },
  {
    id: "stewart",
    name: "Dan H. Stewart",
    title: "Councilman, Ward IV",
    party: "Nonpartisan",
    office: "Henderson City Council, Ward IV",
    region: "Henderson",
    level: "local",
    bio: "Dan Stewart is a fourth-generation Nevadan serving on Henderson City Council. He has a background in engineering, real estate, and public service.",
    keyIssues: ["Infrastructure", "Economic Development", "Public Safety", "Community Planning"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of North Las Vegas
  // ═══════════════════════════════════════════════════════
  {
    id: "goynes-brown",
    name: "Pamela Goynes-Brown",
    title: "Mayor",
    party: "Democrat",
    office: "Mayor of North Las Vegas",
    region: "North Las Vegas",
    level: "local",
    bio: "Pamela Goynes-Brown is the Mayor of North Las Vegas. A former councilwoman, she focuses on economic development, community investment, and infrastructure modernization.",
    keyIssues: ["Economic Development", "Community Investment", "Infrastructure", "Public Safety"],
  },
  {
    id: "barron",
    name: "Isaac Barron",
    title: "Councilman, Ward 1",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 1",
    region: "North Las Vegas",
    level: "local",
    bio: "Isaac Barron serves as North Las Vegas City Councilman for Ward 1, focusing on community engagement, education, and neighborhood improvement.",
    keyIssues: ["Community Engagement", "Education", "Neighborhood Improvement", "Youth Programs"],
  },
  {
    id: "garcia-anderson",
    name: "Ruth Garcia-Anderson",
    title: "Councilwoman, Ward 2",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 2",
    region: "North Las Vegas",
    level: "local",
    bio: "Ruth Garcia-Anderson serves as North Las Vegas City Councilwoman for Ward 2, focusing on community services and public safety.",
    keyIssues: ["Community Services", "Public Safety", "Infrastructure", "Education"],
  },
  {
    id: "black",
    name: "Scott Black",
    title: "Councilman, Ward 3",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 3",
    region: "North Las Vegas",
    level: "local",
    bio: "Scott Black serves as North Las Vegas City Councilman for Ward 3, focusing on economic growth and community development.",
    keyIssues: ["Economic Growth", "Community Development", "Public Safety", "Infrastructure"],
  },
  {
    id: "cherchio",
    name: "Richard Cherchio",
    title: "Councilman, Ward 4",
    party: "Nonpartisan",
    office: "North Las Vegas City Council, Ward 4",
    region: "North Las Vegas",
    level: "local",
    bio: "Richard Cherchio serves as North Las Vegas City Councilman for Ward 4, focusing on veterans' affairs, public safety, and community services.",
    keyIssues: ["Veterans Affairs", "Public Safety", "Community Services", "Infrastructure"],
  },

  // ═══════════════════════════════════════════════════════
  // LOCAL — City of Reno & Sparks
  // ═══════════════════════════════════════════════════════
  {
    id: "schieve",
    name: "Hillary Schieve",
    title: "Mayor",
    party: "Independent",
    office: "Mayor of Reno",
    region: "Reno",
    level: "local",
    bio: "Hillary Schieve has served as Mayor of Reno since 2014. She focuses on economic diversification, homelessness, and downtown revitalization. She is term-limited in 2026.",
    keyIssues: ["Economic Diversification", "Homelessness", "Downtown Revitalization", "Technology"],
  },
  {
    id: "lawson",
    name: "Ed Lawson",
    title: "Mayor",
    party: "Republican",
    office: "Mayor of Sparks",
    region: "Sparks",
    level: "local",
    bio: "Ed Lawson has served as Mayor of Sparks since 2020 and on the city council since 2010. He focuses on managing rapid growth, infrastructure, and public safety.",
    keyIssues: ["Growth Management", "Infrastructure", "Public Safety", "Budget"],
  },
];
